export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';
export const USER_SIGNIN_STARTED = 'USER_SIGNIN_STARTED';

export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNOUT_ERROR = 'USER_SIGNOUT_ERROR';
export const USER_SIGNOUT_STARTED = 'USER_SIGNOUT_STARTED';

export const UPDATE_USER_CURRENT_SESSION = 'UPDATE_USER_CURRENT_SESSION';
export const FAILED_TO_UPDATE_USER_CURRENT_SESSION = 'FAILED_TO_UPDATE_USER_CURRENT_SESSION';

export const GUEST_FORM = 'GUEST_FORM';
export const FINISH_GUEST_FORM = 'FINISH_GUEST_FORM';

export const SET_USER_LEVEL = 'SET_USER_LEVEL';
export const SET_USER_DATA = 'SET_USER_DATA';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const INITIALIZE_FORM_STARTED = 'INITIALIZE_FORM_STARTED';
export const INITIALIZE_FORM_SUCCESS = 'INITIALIZE_FORM_SUCCESS';
